services:
  app:
    image: compose-node-app
    container_name: compose-node-app-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - docker-compose-volume:/node-app/logs
    ports:
      - "3000:8080"
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    container_name: mongocontainer
    volumes:
      - docker-compose-volume:/mongo-data


volumes:
  docker-compose-volume:

