name: hello world
on:
  push:
    branches: 
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world"
        run: echo "Hello world"
      - name : Hello world Action in develop branch
        run: echo "Hello world develop branch is here"